services:
  backend:
    build: ./app        
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: bash -c "python manage.py runserver 0.0.0.0:8000"

  frontend:
    build: ./app/frontend
    ports:
      - "3000:3000"
    volumes:
      - ./app/frontend:/app/frontend