version: '3'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis
      - celery
      - celery-beat
      - frontend

  frontend:
    build: ./app/frontend
    ports:
      - "3000:3000"
    volumes:
      - ./app/frontend:/app/frontend

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    command: redis-server --bind 0.0.0.0
    expose:
      - 6379

  celery:
    build: ./app
    command: celery -A backend worker -l info
    volumes:
      - ./app:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      - redis

  celery-beat:
    build: ./app
    command: celery -A backend beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - redis
      - celery
    environment:
    # - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - REDIS_DB=0