# Generated by Django 4.2.7 on 2023-11-22 19:24

from django.db import migrations


def create_data(apps, schema_editor):
    Airport = apps.get_model('airports', 'Airport')
    Airport(
        airport_name="Katowice-Pyrzowice", 
        city="Katowice", 
        country="Poland"
    ).save()

    Airport(
        airport_name="Krakow-Balice", 
        city="Krakow", 
        country="Poland"
    ).save()

    Airport(
        airport_name="London-Heathrow", 
        city="London", 
        country="England"
    ).save()

    Airport(
        airport_name="Barcelona-El Prat", 
        city="Barcelona", 
        country="Spain"
    ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]