# Generated by Django 4.2.7 on 2023-11-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airport_id', models.AutoField(primary_key=True, serialize=False)),
                ('airport_name', models.CharField(max_length=240, verbose_name='Airport name')),
                ('city', models.CharField(max_length=40, verbose_name='City')),
                ('country', models.CharField(max_length=40, verbose_name='Country')),
            ],
        ),
    ]
