# Generated by Django 4.2.7 on 2023-12-01 19:13

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("username", models.CharField(max_length=30, unique=True)),
                ("password", models.CharField(max_length=128)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="customuser_set",
                        related_query_name="customuser",
                        to="auth.group",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="customuser_set",
                        related_query_name="customuser",
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Airport",
            fields=[
                ("airport_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        default="XXX", max_length=4, verbose_name="Airport code"
                    ),
                ),
                (
                    "airport_name",
                    models.CharField(max_length=240, verbose_name="Airport name"),
                ),
                ("city", models.CharField(max_length=40, verbose_name="City")),
                ("country", models.CharField(max_length=40, verbose_name="Country")),
            ],
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                ("flight_id", models.AutoField(primary_key=True, serialize=False)),
                ("departure_time", models.DateTimeField()),
                ("arrival_time", models.DateTimeField()),
                ("seats", models.IntegerField(default=100)),
                ("ticket_price", models.FloatField(default=0)),
                ("available_seats", models.IntegerField(default=95)),
                (
                    "from_airport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="From_Airport",
                        to="airports.airport",
                    ),
                ),
                (
                    "to_airport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="To_Airport",
                        to="airports.airport",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "List of flights",
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("booking_id", models.AutoField(primary_key=True, serialize=False)),
                ("seats", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("0", "Booked"),
                            ("1", "Confirmed"),
                            ("2", "Cancelled"),
                        ],
                        default=0,
                        max_length=2,
                    ),
                ),
                ("booking_time", models.DateTimeField(auto_now=True)),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "flight_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="airports.flight",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "List of bookings",
            },
        ),
    ]
