# Generated by Django 4.2.7 on 2023-11-23 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airport_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='XXX', max_length=4, verbose_name='Airport code')),
                ('airport_name', models.CharField(max_length=240, verbose_name='Airport name')),
                ('city', models.CharField(max_length=40, verbose_name='City')),
                ('country', models.CharField(max_length=40, verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'List of clients',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.AutoField(primary_key=True, serialize=False)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('seats', models.IntegerField(default=100)),
                ('ticket_price', models.FloatField(default=0)),
                ('available_seats', models.IntegerField(default=95)),
                ('from_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='From_Airport', to='airports.airport')),
                ('to_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='To_Airport', to='airports.airport')),
            ],
            options={
                'verbose_name_plural': 'List of flights',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('seats', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('0', 'Booked'), ('1', 'Confirmed'), ('2', 'Cancelled')], default=0, max_length=2)),
                ('booking_time', models.DateTimeField(auto_now=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airports.client')),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airports.flight')),
            ],
            options={
                'verbose_name_plural': 'List of bookings',
            },
        ),
    ]
