# Generated by Django 4.2.7 on 2023-12-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
